# sparql/sparql4.sparql
PREFIX sc: <urn:soap/crime/ontology#>

select * where {
    ?p1 a sc:LeakInfoSourcePeople .
    ?p2 a sc:LeakInfoDestinationPeople.
    ?p1 (sc:isPartOfConversation/sc:hasConversationParticipant)* ?p2
}